services:
  postgres-pg:
    image: postgres:16.0-alpine3.18
    env_file:
      .env.development
    ports:
      - "5433:5432"
  postgres-sequelize:
    image: postgres:16.0-alpine3.18
    env_file:
      .env.development
    ports:
      - "5434:5432"
  postgres-prisma:
    image: postgres:16.0-alpine3.18
    env_file:
      .env.development
    ports:
      - "5435:5432"    
  postgres-typeorm:
    image: postgres:16.0-alpine3.18
    env_file:
      .env.development
    ports:
      - "5436:5432"
